# Generated by Django 5.2 on 2026-09-26 07:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='address_line1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vendor',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vendor',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator('^\\+?[0-9]{10,15}$', 'Enter 10–15 digits, optionally starting with +.')]),
        ),
        migrations.AddField(
            model_name='vendor',
            name='business_description',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='vendor',
            name='business_type',
            field=models.CharField(blank=True, choices=[('SOLE_PROPRIETOR', 'Sole proprietor'), ('PARTNERSHIP', 'Partnership'), ('LLP', 'Limited liability partnership'), ('COMPANY', 'Company'), ('OTHER', 'Other')], max_length=30),
        ),
        migrations.AddField(
            model_name='vendor',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator('^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][1-9A-Z]Z[0-9A-Z]$', 'Enter a valid 15-character GSTIN format.')]),
        ),
        migrations.AddField(
            model_name='vendor',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='legal_business_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vendor',
            name='postal_code',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9][A-Za-z0-9 -]{1,11}$', 'Enter a valid postal code.')]),
        ),
        migrations.AddField(
            model_name='vendor',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
