# Generated by Django 5.2 on 2026-09-26 10:32

import django.core.validators
import django.db.models.deletion
import vendors.models
from django.conf import settings
from django.db import migrations, models


def copy_crm_fields(apps, schema_editor):
    Vendor = apps.get_model("vendors", "Vendor")
    Designer = apps.get_model("designers", "Designer")
    alias = schema_editor.connection.alias
    fields = ["brand_name", "city", "primary_category", "lead_source", "sales_owner", "next_followup_date", "tier", "online_membership_plan", "credit_points", "take_rate", "acquisition_cost", "renewal_likelihood", "contract_end_date", "stage", "kyc_status", "follow_up_tasks", "lost_reason", "contract_signed"]
    for record in Designer.objects.using(alias).all().iterator():
        vendor = Vendor.objects.using(alias).filter(crm_record_id=record.pk).first()
        if vendor is None:
            vendor = Vendor(crm_record_id=record.pk, email=record.email or None, phone=record.phone or None, gst_number=record.gst_number or "")
        for field in fields:
            value = getattr(record, field)
            model_field = Vendor._meta.get_field(field)
            if value is None and not model_field.null:
                value = model_field.get_default() if model_field.has_default() else ""
            setattr(vendor, field, value)
        vendor.vendor_name = record.designer_name
        vendor.vendor_code = vendors.models.vendor_code()
        vendor.save(using=alias)
    for vendor in Vendor.objects.using(alias).filter(vendor_code__isnull=True):
        vendor.vendor_code = vendors.models.vendor_code()
        vendor.save(using=alias, update_fields=["vendor_code"])


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0007_designer_credit_points'),
        ('vendors', '0002_vendor_address_line1_vendor_address_line2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(model_name="vendor", name="lost_reason", field=models.CharField(max_length=255, blank=True)),
        migrations.AddField(model_name="vendor", name="contract_signed", field=models.BooleanField(default=False)),
        migrations.AddField(
            model_name='vendor',
            name='acquisition_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='vendor',
            name='brand_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='vendor',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='contract_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='credit_points',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendor',
            name='follow_up_tasks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='vendor',
            name='kyc_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='vendor',
            name='lead_source',
            field=models.CharField(choices=[('Referral', 'Referral'), ('Outreach', 'Outreach'), ('Inbound', 'Inbound'), ('Instagram', 'Instagram'), ('Trade Show', 'Trade Show'), ('Agency', 'Agency')], default='Referral', max_length=30),
        ),
        migrations.AddField(
            model_name='vendor',
            name='next_followup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='online_membership_plan',
            field=models.CharField(blank=True, choices=[('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum'), ('PALLADIUM', 'Palladium')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='primary_category',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='vendor',
            name='renewal_likelihood',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='vendor',
            name='sales_owner',
            field=models.CharField(choices=[('Nisha Kapoor', 'Nisha Kapoor'), ('Dev Ranganathan', 'Dev Ranganathan'), ('Sana Qureshi', 'Sana Qureshi'), ('Unassigned', 'Unassigned')], default='Unassigned', max_length=150),
        ),
        migrations.AddField(
            model_name='vendor',
            name='stage',
            field=models.CharField(choices=[('LEAD', 'Lead'), ('QUALIFIED', 'Qualified'), ('PORTFOLIO', 'Portfolio'), ('REVIEW', 'Review'), ('APPROVED', 'Approved'), ('CONTRACT', 'Contract'), ('SIGNED', 'Signed'), ('LIVE', 'Live'), ('ACTIVE', 'Active'), ('REJECTED', 'Rejected'), ('INACTIVE', 'Inactive')], default='LEAD', max_length=20),
        ),
        migrations.AddField(
            model_name='vendor',
            name='take_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='vendor',
            name='tier',
            field=models.CharField(choices=[('PREMIUM', 'Premium'), ('CORE', 'Core'), ('EMERGING', 'Emerging')], default='EMERGING', max_length=20),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_code',
            field=models.CharField(null=True, max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='crm_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendor_registration', to='designers.designer'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\+?[0-9]{10,15}$', 'Enter 10–15 digits, optionally starting with +.')]),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(copy_crm_fields, migrations.RunPython.noop),
        migrations.AlterField(model_name="vendor", name="vendor_code", field=models.CharField(default=vendors.models.vendor_code, max_length=30, unique=True)),
    ]
