# Generated by Django 5.2 on 2026-09-26 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0004_onlinevendorcredit_and_more'),
        ('vendors', '0003_vendor_acquisition_cost_vendor_brand_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='plan_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendors', to='credits.onlinevendorcredit'),
        ),
    ]
