# Generated by Django 5.2 on 2026-09-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_link_vendor_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='vendors/logos/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='vendors/profiles/'),
        ),
    ]
