# Generated by Django 6.1.1 on 2026-09-09 09:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('sku', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='SKU')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Product Description')),
                ('designer', models.CharField(max_length=255, verbose_name='Designer')),
                ('category', models.CharField(max_length=150, verbose_name='Category')),
                ('subcategory', models.CharField(blank=True, max_length=150, null=True, verbose_name='Subcategory')),
                ('colour', models.CharField(max_length=100, verbose_name='Colour')),
                ('size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('FREE', 'Free Size')], default='FREE', max_length=20, verbose_name='Size')),
                ('material', models.CharField(blank=True, max_length=150, null=True, verbose_name='Material')),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='MRP')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Selling Price')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Discount Percentage')),
                ('inventory_quantity', models.PositiveIntegerField(default=0, verbose_name='Inventory Quantity')),
                ('low_stock_threshold', models.PositiveIntegerField(default=5, verbose_name='Low Stock Threshold')),
                ('fulfilment_location', models.CharField(choices=[('MUMBAI_FC', 'Mumbai FC'), ('BANGALORE_FC', 'Bangalore FC'), ('DELHI_FC', 'Delhi FC'), ('DESIGNER_STUDIO', 'Designer Studio')], max_length=100, verbose_name='Fulfilment Location')),
                ('fast_delivery', models.BooleanField(default=False, verbose_name='Fast Delivery')),
                ('return_policy', models.CharField(choices=[('RETURNABLE', 'Returnable'), ('FINAL_SALE', 'Final Sale')], default='RETURNABLE', max_length=30, verbose_name='Return Policy')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_QA', 'Pending QA'), ('APPROVED', 'Approved'), ('LIVE', 'Live'), ('REJECTED', 'Rejected'), ('INACTIVE', 'Inactive')], db_index=True, default='DRAFT', max_length=30, verbose_name='Product Status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_live', models.BooleanField(default=False, verbose_name='Live on Storefront')),
                ('primary_image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Primary Product Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'product',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sku'], name='product_sku_afe0af_idx'), models.Index(fields=['status'], name='product_status_407ffb_idx'), models.Index(fields=['category'], name='product_categor_4f5ce7_idx'), models.Index(fields=['designer'], name='product_designe_7bc7f7_idx'), models.Index(fields=['is_live'], name='product_is_live_e46454_idx'), models.Index(fields=['is_active'], name='product_is_acti_916801_idx')],
            },
        ),
    ]
