# Generated by Django 6.1.1 on 2026-09-10 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='product_designe_7335c5_idx',
            old_name='product_designe_7bc7f7_idx',
        ),
        migrations.AlterField(
            model_name='product',
            name='designer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='designers.designer', verbose_name='Designer'),
        ),
    ]
