# Generated by Django 6.1.1 on 2026-09-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_product_designe_7bc7f7_idx_product_designe_7335c5_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_QA', 'Pending QA'), ('CORRECTION', 'Needs Correction'), ('APPROVED', 'Approved'), ('LIVE', 'Live'), ('REJECTED', 'Rejected'), ('INACTIVE', 'Inactive')], db_index=True, default='DRAFT', max_length=30, verbose_name='Product Status'),
        ),
    ]
