# Generated by Django 6.1.1 on 2026-09-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_qa_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='damaged_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Damaged Quantity'),
        ),
        migrations.AddField(
            model_name='product',
            name='in_transit_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='In-Transit Quantity'),
        ),
        migrations.AddField(
            model_name='product',
            name='quarantined_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Quarantined Quantity'),
        ),
        migrations.AddField(
            model_name='product',
            name='reserved_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Reserved Quantity'),
        ),
        migrations.AddField(
            model_name='product',
            name='returned_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Returned Quantity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='inventory_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Physical Inventory Quantity'),
        ),
    ]
