# Generated by Django 6.0.8 on 2026-09-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_damaged_quantity_product_in_transit_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pet_safety',
            field=models.TextField(blank=True, default='No loose beads. Breathable fabric. Supervised wear recommended.', verbose_name='Pet Safety Information'),
        ),
    ]
