# Generated by Django 6.0.8 on 2026-09-15 09:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_pet_safety'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='alt_text',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Image Alt Text'),
        ),
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Barcode / EAN'),
        ),
        migrations.AddField(
            model_name='product',
            name='bestseller',
            field=models.BooleanField(default=False, verbose_name='Bestseller'),
        ),
        migrations.AddField(
            model_name='product',
            name='care',
            field=models.TextField(blank=True, default='Dry clean only or gentle hand wash.', verbose_name='Care Instructions'),
        ),
        migrations.AddField(
            model_name='product',
            name='collection',
            field=models.CharField(blank=True, default='Diwali Luxe', max_length=100, verbose_name='Collection'),
        ),
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, default='25x20x3 cm', max_length=100, verbose_name='Dimensions'),
        ),
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Featured'),
        ),
        migrations.AddField(
            model_name='product',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('12.00'), max_digits=5, verbose_name='GST Rate (%)'),
        ),
        migrations.AddField(
            model_name='product',
            name='hsn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='HSN Code'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Image URL'),
        ),
        migrations.AddField(
            model_name='product',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Search Keywords'),
        ),
        migrations.AddField(
            model_name='product',
            name='limited_edition',
            field=models.BooleanField(default=False, verbose_name='Limited Edition'),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.TextField(blank=True, default='Crafted in India', verbose_name='Manufacturing Information'),
        ),
        migrations.AddField(
            model_name='product',
            name='new_arrival',
            field=models.BooleanField(default=True, verbose_name='New Arrival'),
        ),
        migrations.AddField(
            model_name='product',
            name='occasion',
            field=models.CharField(blank=True, default='Festive', max_length=100, verbose_name='Occasion'),
        ),
        migrations.AddField(
            model_name='product',
            name='origin',
            field=models.CharField(blank=True, default='India', max_length=100, verbose_name='Country of Origin'),
        ),
        migrations.AddField(
            model_name='product',
            name='season',
            field=models.CharField(blank=True, default='AW 2026', max_length=100, verbose_name='Season'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_description',
            field=models.TextField(blank=True, default='', verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Video URL'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_g',
            field=models.PositiveIntegerField(blank=True, default=250, verbose_name='Weight (g)'),
        ),
    ]
