# Generated by Django 6.0.8 on 2026-09-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_alt_text_product_barcode_product_bestseller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qa_note',
            field=models.TextField(blank=True, default='', verbose_name='QA Reviewer Note'),
        ),
        migrations.AddField(
            model_name='product',
            name='qa_scores',
            field=models.JSONField(blank=True, default=dict, verbose_name='QA Dimension Scores'),
        ),
    ]
