# Generated by Django 5.2 on 2026-09-19 07:11

import django.core.files.storage
import django.core.validators
import django.db.models.deletion
import pathlib
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_qa_note_product_qa_scores'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(choices=[(1, 'Image 1'), (2, 'Image 2'), (3, 'Image 3'), (4, 'Image 4')])),
                ('image', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location=pathlib.PureWindowsPath('C:/Users/Lenovo T470/Desktop/zenve_fashion_crm/fashion_crm/Zenve_Fashion_Backend/private_uploads')), upload_to=products.models.product_image_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='products.product')),
            ],
            options={
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('product', 'position'), name='unique_product_image_position')],
            },
        ),
    ]
