# Generated by Django 5.2 on 2026-09-24 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sales_channel',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('BOTH', 'Online & Offline')], db_index=True, default='ONLINE', help_text='Choose Online, Offline, or both.', max_length=20, verbose_name='Sales Channel'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fulfilment_location',
            field=models.CharField(choices=[('MUMBAI_FC', 'Mumbai FC'), ('BENGALURU_FC', 'Bengaluru FC'), ('KOCHI_FC', 'Kochi FC'), ('CHENNAI_FC', 'Chennai FC')], max_length=100, verbose_name='Fulfilment Location'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('FREE', 'Free Size')], max_length=20, null=True, verbose_name='Legacy Single Size'),
        ),
        migrations.CreateModel(
            name='ProductSizeStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('FREE', 'Free Size')], max_length=20, verbose_name='Size')),
                ('online_quantity', models.PositiveIntegerField(default=0, verbose_name='Online Quantity')),
                ('offline_quantity', models.PositiveIntegerField(default=0, verbose_name='Offline Store Quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_stocks', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Size Stock',
                'verbose_name_plural': 'Product Size Stocks',
                'db_table': 'product_size_stock',
                'ordering': ['product_id', 'id'],
                'indexes': [models.Index(fields=['product', 'size'], name='product_siz_product_b3e813_idx')],
                'constraints': [models.UniqueConstraint(fields=('product', 'size'), name='unique_product_size_stock')],
            },
        ),
    ]
