# Generated by Django 5.2 on 2026-09-26 12:33

import django.core.files.storage
import django.core.validators
import pathlib
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_mediajob_mediaasset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fulfilment_location',
            field=models.CharField(choices=[('MUMBAI_FC', 'Mumbai FC'), ('BENGALURU_FC', 'Bengaluru FC'), ('BANGALORE_FC', 'Bangalore FC'), ('KOCHI_FC', 'Kochi FC'), ('CHENNAI_FC', 'Chennai FC'), ('DELHI_FC', 'Delhi FC'), ('DESIGNER_STUDIO', 'Designer Studio')], max_length=100, verbose_name='Fulfilment Location'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location=pathlib.PureWindowsPath('C:/Users/Lenovo T470/Desktop/zippy/zippy_vender_crm/vendor_crm_Backend/private_uploads')), upload_to=products.models.product_image_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
