# Generated by Django 5.2 on 2026-09-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineFashionCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum'), ('PALLADIUM', 'Palladium')], db_index=True, max_length=20, unique=True)),
                ('membership_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('original_membership_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit_points', models.PositiveBigIntegerField(default=0)),
                ('included_catalogue', models.PositiveIntegerField(default=0)),
                ('per_showroom', models.PositiveIntegerField(default=0)),
                ('extra_catalogue', models.PositiveIntegerField(default=0)),
                ('extra_per_showroom', models.PositiveIntegerField(default=0)),
                ('min_days', models.PositiveIntegerField(default=0)),
                ('average_sku', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Offline Fashion Credit',
                'verbose_name_plural': 'Offline Fashion Credits',
                'db_table': 'offline_fashion_credit',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OnlineFashionCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum'), ('PALLADIUM', 'Palladium')], db_index=True, max_length=20, unique=True)),
                ('catalogue', models.PositiveIntegerField(default=0)),
                ('products', models.PositiveIntegerField(default=0)),
                ('credit_points', models.PositiveBigIntegerField(default=0)),
                ('catalogue_charge_points', models.PositiveIntegerField(default=0)),
                ('min_days', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Online Fashion Credit',
                'verbose_name_plural': 'Online Fashion Credits',
                'db_table': 'online_fashion_credit',
                'ordering': ['id'],
            },
        ),
    ]
