# Generated by Django 6.0.8 on 2026-09-25 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
        ('designers', '0007_designer_credit_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offlinefashioncredit',
            name='plan',
            field=models.CharField(choices=[('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum'), ('PALLADIUM', 'Palladium'), ('PALLADIUM++', 'Palladium++')], db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='onlinefashioncredit',
            name='plan',
            field=models.CharField(choices=[('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum'), ('PALLADIUM', 'Palladium'), ('PALLADIUM++', 'Palladium++')], db_index=True, max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='DesignerCreditWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online_credits', models.PositiveBigIntegerField(default=72464, verbose_name='Online Credits (Free)')),
                ('offline_credits', models.PositiveBigIntegerField(default=37480, verbose_name='Offline Credits (Paid)')),
                ('points_used', models.PositiveBigIntegerField(default=27556, verbose_name='Points Used')),
                ('online_plan', models.CharField(default='Silver', max_length=50, verbose_name='Online Plan')),
                ('offline_plan', models.CharField(default='Gold', max_length=50, verbose_name='Offline Plan')),
                ('offline_pack_expiry', models.DateField(blank=True, null=True, verbose_name='Offline Pack Expiry')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('designer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_wallet', to='designers.designer')),
            ],
            options={
                'verbose_name': 'Designer Credit Wallet',
                'verbose_name_plural': 'Designer Credit Wallets',
                'db_table': 'designer_credit_wallet',
            },
        ),
        migrations.CreateModel(
            name='DesignerCreditStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('channel', models.CharField(choices=[('ONLINE', 'ONLINE'), ('OFFLINE', 'OFFLINE')], default='ONLINE', max_length=20, verbose_name='Channel')),
                ('points', models.IntegerField(verbose_name='Points Change')),
                ('date_str', models.CharField(blank=True, max_length=30, null=True, verbose_name='Display Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_statements', to='designers.designer')),
                ('wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='credits.designercreditwallet')),
            ],
            options={
                'verbose_name': 'Designer Credit Statement',
                'verbose_name_plural': 'Designer Credit Statements',
                'db_table': 'designer_credit_statement',
                'ordering': ['-id'],
            },
        ),
    ]
