# Generated by Django 5.2 on 2026-09-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0003_update_online_plan_credits'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineVendorCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('credit_points', models.PositiveBigIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'online_vendor_credit',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
