# Generated by Django 5.2 on 2026-09-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0006_vendor_plan_sku_limits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designercreditwallet',
            name='offline_credits',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Offline Credits (Paid)'),
        ),
        migrations.AlterField(
            model_name='designercreditwallet',
            name='offline_plan',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Offline Plan'),
        ),
        migrations.AlterField(
            model_name='designercreditwallet',
            name='online_credits',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Online Credits (Free)'),
        ),
        migrations.AlterField(
            model_name='designercreditwallet',
            name='online_plan',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Online Plan'),
        ),
        migrations.AlterField(
            model_name='designercreditwallet',
            name='points_used',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Points Used'),
        ),
    ]
