from decimal import Decimal
from django.db.models import Sum, Count, Q
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from rest_framework.permissions import AllowAny

from vendors.models import Vendor as Designer
from products.models import Product
from orders.models import Order, OrderItem, ReturnRequest, Settlement


class CommandCentreOverviewAPIView(APIView):
    """
    Returns high-level governance metrics for Layer 12 Command Centre:
    - Executive KPIs (Open Exceptions, GMV Booked, Sellable Units, Active Designers)
    - Pending Approvals across all 5 operational clearance layers
    - Dynamic Exceptions and Automation Alerts generated by blueprint rules
    - Chronological Cross-Layer Audit Log
    - Operational Reports Row Counts
    """
    permission_classes = [AllowAny]

    def get(self, request):
        # 1. Orders and GMV
        non_cancelled_orders = Order.objects.exclude(order_status__in=["Cancelled", "CANCELLED"])
        orders_count = non_cancelled_orders.count()
        gmv_agg = non_cancelled_orders.aggregate(total=Sum("total"))
        gmv_decimal = gmv_agg["total"] or Decimal("0.00")
        gmv_float = float(gmv_decimal)

        # 2. Inventory & Products
        products = Product.objects.select_related("designer").all()
        products_count = products.count()
        sellable_units = sum(p.available_quantity for p in products)

        # 3. Designers
        designers = Designer.objects.all()
        active_designers_count = designers.filter(stage__in=["SIGNED", "LIVE", "ACTIVE"]).count()
        if active_designers_count == 0 and designers.exists():
            active_designers_count = designers.count()

        # 4. Pending Approvals
        skus_pending_qa = products.filter(
            status__in=[
                Product.ProductStatus.PENDING_QA,
                Product.ProductStatus.DRAFT,
                Product.ProductStatus.CORRECTION,
            ]
        ).count()

        designers_awaiting_contract = designers.filter(
            Q(contract_signed=False) | ~Q(stage__in=[Designer.Stage.SIGNED, Designer.Stage.LIVE, Designer.Stage.ACTIVE])
        ).count()

        returns_awaiting_inspection = ReturnRequest.objects.filter(
            status__in=[
                ReturnRequest.ReturnStatus.REQUESTED,
                ReturnRequest.ReturnStatus.PICKUP_SCHEDULED,
                ReturnRequest.ReturnStatus.RECEIVED,
            ]
        ).count()

        settlements_to_approve = Settlement.objects.filter(
            status=Settlement.SettlementStatus.PENDING
        ).count()

        orders_to_dispatch = Order.objects.filter(
            order_status__in=[
                "Pending",
                "Confirmed",
                "Processing",
                "PLACED",
                "CONFIRMED",
                "PACKED",
            ]
        ).count()

        pending_approvals = {
            "skus_pending_qa": skus_pending_qa,
            "designers_awaiting_contract": designers_awaiting_contract,
            "returns_awaiting_inspection": returns_awaiting_inspection,
            "settlements_to_approve": settlements_to_approve,
            "orders_to_dispatch": orders_to_dispatch,
        }

        # 5. Dynamic Exceptions & Automation Alerts
        exceptions = []

        # Rule A: Fast Delivery Promise Safety Rule
        for p in products:
            if p.fast_delivery and p.available_quantity <= 0:
                exceptions.append({
                    "type": "Delivery",
                    "text": f"Fast promise unsafe on {p.product_name} ({p.sku}) — no available stock",
                    "severity": "danger",
                    "layer": "Delivery Engine",
                    "path": "/delivery",
                })

        # Rule B: Low Stock / Out of Stock Thresholds
        for p in products:
            if p.available_quantity == 0:
                exceptions.append({
                    "type": "Inventory",
                    "text": f"Out of stock: {p.product_name} ({p.sku}) — 0 available",
                    "severity": "warning",
                    "layer": "Inventory Engine",
                    "path": "/inventory",
                })
            elif p.available_quantity <= p.low_stock_threshold:
                exceptions.append({
                    "type": "Inventory",
                    "text": f"Low stock alert: {p.product_name} ({p.sku}) only {p.available_quantity} available",
                    "severity": "warning",
                    "layer": "Inventory Engine",
                    "path": "/inventory",
                })

        # Rule C: Catalogue QA Pending
        for p in products:
            if p.status in [Product.ProductStatus.PENDING_QA, Product.ProductStatus.CORRECTION]:
                exceptions.append({
                    "type": "QA",
                    "text": f"{p.sku} pending QA review ({p.status})",
                    "severity": "warning",
                    "layer": "Catalogue QA",
                    "path": "/catalogue-qa",
                })

        # Rule D: Returns Engine Failed QC or Uninspected
        returns_all = ReturnRequest.objects.select_related("order", "order_item").all()
        for r in returns_all:
            if r.status == ReturnRequest.ReturnStatus.INSPECTED_FAILED:
                exceptions.append({
                    "type": "Returns",
                    "text": f"{r.return_number} failed QC inspection — quarantine hold",
                    "severity": "danger",
                    "layer": "Returns Engine",
                    "path": "/returns",
                })
            elif r.status in [ReturnRequest.ReturnStatus.REQUESTED, ReturnRequest.ReturnStatus.RECEIVED]:
                exceptions.append({
                    "type": "Returns",
                    "text": f"{r.return_number} awaiting warehouse inspection",
                    "severity": "warning",
                    "layer": "Returns Engine",
                    "path": "/returns",
                })

        # Rule E: Finance Pending Settlements
        pending_settlements = Settlement.objects.filter(status=Settlement.SettlementStatus.PENDING).select_related("designer")
        for s in pending_settlements:
            brand = s.designer.brand_name if s.designer else "Designer"
            exceptions.append({
                "type": "Finance",
                "text": f"Settlement {s.settlement_number} ({brand}) pending payout approval",
                "severity": "warning",
                "layer": "Settlement",
                "path": "/settlement",
            })

        # Rule F: Designer CRM KYC/Contract Review
        for d in designers:
            if not d.contract_signed or d.stage not in [Designer.Stage.SIGNED, Designer.Stage.LIVE, Designer.Stage.ACTIVE]:
                exceptions.append({
                    "type": "CRM",
                    "text": f"{d.brand_name} stage: {d.stage} (KYC: {d.kyc_status}) — contract review required",
                    "severity": "danger",
                    "layer": "Designer CRM",
                    "path": "/designer-crm",
                })

        # 6. Executive KPIs
        kpis = {
            "open_exceptions": len(exceptions),
            "gmv_booked": f"₹{int(gmv_float):,}" if gmv_float >= 1000 else f"₹{gmv_float:.2f}",
            "raw_gmv": gmv_float,
            "orders_count": f"{orders_count} orders",
            "raw_orders_count": orders_count,
            "sellable_units": sellable_units,
            "active_designers": active_designers_count,
        }

        # 7. Cross-Layer Audit Log
        audit_logs = []

        # From Orders
        for o in Order.objects.order_by("-created_at")[:15]:
            audit_logs.append({
                "date": o.created_at.strftime("%d/%m/%y, %I:%M %p") if o.created_at else "",
                "timestamp": o.created_at.isoformat() if o.created_at else "",
                "layer": "OMS",
                "event": f"Order {o.order_number} placed by {o.shipping_full_name} (Status: {o.order_status})",
            })

        # From Returns
        for r in ReturnRequest.objects.order_by("-created_at")[:15]:
            sku = r.order_item.sku if r.order_item else ""
            audit_logs.append({
                "date": r.created_at.strftime("%d/%m/%y, %I:%M %p") if r.created_at else "",
                "timestamp": r.created_at.isoformat() if r.created_at else "",
                "layer": "Returns",
                "event": f"Return {r.return_number} logged for {sku} (Status: {r.status})",
            })

        # From Settlements
        for s in Settlement.objects.order_by("-created_at")[:15]:
            brand = s.designer.brand_name if s.designer else ""
            reversal_str = " (Reversal)" if s.is_reversal else ""
            audit_logs.append({
                "date": s.created_at.strftime("%d/%m/%y, %I:%M %p") if s.created_at else "",
                "timestamp": s.created_at.isoformat() if s.created_at else "",
                "layer": "Settlement",
                "event": f"Settlement {s.settlement_number} for {brand}{reversal_str} (Status: {s.status})",
            })

        # From Products
        for p in Product.objects.order_by("-updated_at")[:10]:
            audit_logs.append({
                "date": p.updated_at.strftime("%d/%m/%y, %I:%M %p") if p.updated_at else "",
                "timestamp": p.updated_at.isoformat() if p.updated_at else "",
                "layer": "Catalogue QA",
                "event": f"SKU {p.sku} ({p.product_name}) QA Status: {p.status} (Stock: {p.available_quantity})",
            })

        # From Designers
        for d in Designer.objects.order_by("-created_at")[:10]:
            audit_logs.append({
                "date": d.created_at.strftime("%d/%m/%y, %I:%M %p") if hasattr(d, "created_at") and d.created_at else "",
                "timestamp": d.created_at.isoformat() if hasattr(d, "created_at") and d.created_at else "",
                "layer": "Designer CRM",
                "event": f"Designer {d.brand_name} registered (Stage: {d.stage}, KYC: {d.kyc_status})",
            })

        # Workspace initialisation baseline
        audit_logs.append({
            "date": "29/08/26, 12:22 pm",
            "timestamp": "2026-08-29T12:22:00",
            "layer": "Admin",
            "event": "Workspace initialised with seed catalogue and ledger.",
        })

        # Sort all logs by timestamp descending
        audit_logs.sort(key=lambda x: x["timestamp"], reverse=True)

        # 8. Operational Reports Row Counts
        reports = [
            {"id": "executive_summary", "title": "Executive summary", "rows": f"{len(exceptions) + 6} rows"},
            {"id": "designers", "title": "Designers", "rows": f"{designers.count()} rows"},
            {"id": "sku_inventory", "title": "SKU & inventory", "rows": f"{products_count} rows"},
            {"id": "orders", "title": "Orders", "rows": f"{Order.objects.count()} rows"},
            {"id": "returns", "title": "Returns", "rows": f"{ReturnRequest.objects.count()} rows"},
            {"id": "settlements", "title": "Settlements", "rows": f"{Settlement.objects.count()} rows"},
            {"id": "audit_log", "title": "Audit log", "rows": f"{len(audit_logs)} rows"},
        ]

        return Response({
            "kpis": kpis,
            "pending_approvals": pending_approvals,
            "exceptions": exceptions,
            "audit_logs": audit_logs,
            "reports": reports,
        }, status=status.HTTP_200_OK)
