# Generated by Django 5.2 on 2026-09-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Merchandiser', 'Merchandiser'), ('Catalogue QA', 'Catalogue QA'), ('Operations', 'Operations'), ('Finance', 'Finance'), ('Media', 'Media'), ('Other', 'Other')], max_length=50),
        ),
    ]
