# Generated by Django 6.1.1 on 2026-09-10 09:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, unique=True, verbose_name='Order Number'),
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(blank=True, db_index=True, max_length=100, unique=True, verbose_name='Return Number')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Returned Quantity')),
                ('reason', models.CharField(choices=[('SIZE_FIT', 'Size / Fit Issue'), ('DEFECTIVE', 'Defective / Damaged Item'), ('WRONG_ITEM', 'Wrong Item Delivered'), ('QUALITY_ISSUE', 'Quality Not as Expected'), ('NOT_NEEDED', 'No Longer Needed'), ('OTHER', 'Other')], default='SIZE_FIT', max_length=50, verbose_name='Reason for Return')),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('PICKUP_SCHEDULED', 'Pickup Scheduled'), ('RECEIVED', 'Received at Warehouse'), ('INSPECTED_PASSED', 'Inspected - Passed'), ('INSPECTED_FAILED', 'Inspected - Failed QC'), ('REFUNDED', 'Refunded'), ('REJECTED', 'Rejected')], db_index=True, default='REQUESTED', max_length=30, verbose_name='Return Status')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Refund Amount')),
                ('pickup_pincode', models.CharField(blank=True, max_length=10, null=True, verbose_name='Pickup Pincode')),
                ('pickup_address', models.TextField(blank=True, null=True, verbose_name='Pickup Address')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Customer / Return Notes')),
                ('inspection_notes', models.TextField(blank=True, null=True, verbose_name='Inspection / QC Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='orders.order', verbose_name='Order')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='orders.orderitem', verbose_name='Order Item')),
            ],
            options={
                'verbose_name': 'Return Request',
                'verbose_name_plural': 'Return Requests',
                'db_table': 'orders_return_request',
                'ordering': ['-created_at'],
            },
        ),
    ]
