# Generated by Django 6.1.1 on 2026-09-10 09:59

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0001_initial'),
        ('orders', '0002_alter_order_order_number_returnrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_number', models.CharField(blank=True, db_index=True, max_length=100, unique=True, verbose_name='Settlement Number')),
                ('is_reversal', models.BooleanField(default=False, verbose_name='Is Reversal')),
                ('gmv', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Gross Merchandise Value (GMV)')),
                ('take_rate', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5, verbose_name='Take Rate (%)')),
                ('commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Zenve Commission')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Tax (GST)')),
                ('payout_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Payable to Designer')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('RECONCILED', 'Reconciled'), ('REVERSED', 'Reversed by Return')], db_index=True, default='PENDING', max_length=30, verbose_name='Settlement Status')),
                ('payout_reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Payout Reference / UTR')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Paid At')),
                ('reconciled_at', models.DateTimeField(blank=True, null=True, verbose_name='Reconciled At')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Settlement Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='designers.designer', verbose_name='Designer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='orders.order', verbose_name='Order')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='orders.orderitem', verbose_name='Order Item')),
                ('return_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversal_settlements', to='orders.returnrequest', verbose_name='Associated Return')),
            ],
            options={
                'verbose_name': 'Settlement',
                'verbose_name_plural': 'Settlements',
                'db_table': 'orders_settlement',
                'ordering': ['-created_at'],
            },
        ),
    ]
