# Generated by Django 5.2 on 2026-09-19 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderitem',
            table='orders_orderitem',
        ),
    ]
